/**
 * Networked shell around WorldImpl: lobby, countdown, joins, message routing.
 * All gameplay lives in systems; this file does not know any rules.
 *
 * Owned by the integrator. Agents do not edit this file.
 */

import { Room, type Client } from 'colyseus';
import {
  BOSS, CLASSES, CLASS_IDS, CRYSTALS, MAP, MATCH, PATCH_RATE, PLAYER, PROGRESSION,
  PROTOCOL_VERSION, ROOM_CODE_ALPHABET, ROOM_CODE_LENGTH, TICK_MS,
  ClientMessage, JoinError, MatchPhase, Outcome, ServerMessage,
  type AttackPayload, type ClassId, type InteractPayload, type JoinOptions, type MovePayload,
  type PickClassPayload, type SpendSkillPointPayload, type System, type UseAbilityPayload,
} from '@redbox/shared';
import { MatchState, Player } from '@redbox/shared/schema';
import { WorldImpl } from './world.js';

export class HeistRoom extends Room<MatchState> {
  maxClients = MATCH.TEAM_SIZE;

  /** Set by index.ts: stub systems for the frontend, real systems otherwise. */
  static systemFactory: () => System[] = () => [];

  world!: WorldImpl;
  private countdownStartedAt = 0;
  private countdownElapsed = 0;

  onCreate(options: { roomCode?: string } = {}) {
    const state = createMatchState(options.roomCode ?? randomRoomCode());
    this.setState(state);
    this.setMetadata({ roomCode: state.roomCode });
    this.setPatchRate(1000 / PATCH_RATE);

    this.world = new WorldImpl(state, (type, payload) => this.broadcast(type, payload), HeistRoom.systemFactory());
    this.registerMessageHandlers();

    // 0.16 has no fixed-timestep helper; clamp the measured delta so a GC hitch
    // can never teleport entities across the map.
    this.setSimulationInterval((deltaMs) => this.tick(Math.min(deltaMs, TICK_MS * 3)), TICK_MS);
  }

  onJoin(client: Client, options: JoinOptions) {
    if (options?.protocolVersion !== PROTOCOL_VERSION) {
      client.send(ServerMessage.Error, {
        code: JoinError.ProtocolMismatch,
        message: `server speaks v${PROTOCOL_VERSION}, client sent v${options?.protocolVersion}`,
      });
      throw new Error(JoinError.ProtocolMismatch);
    }
    if (this.state.phase !== MatchPhase.Lobby) throw new Error(JoinError.MatchInProgress);
    addPlayer(this.state, client.sessionId, options?.name || 'player', this.assignClass(options?.classId), false);
  }

  onLeave(client: Client) {
    const p = this.state.players.get(client.sessionId);
    if (!p) return;
    p.connected = false;
    // Mid-match, the seat becomes a bot rather than dropping a role.
    if (this.state.phase === MatchPhase.Lobby) this.state.players.delete(client.sessionId);
    else p.isBot = true;
  }

  private registerMessageHandlers() {
    this.onMessage(ClientMessage.Move, (client, msg: MovePayload) => {
      this.world.setIntent(client.sessionId, Number(msg?.dx) || 0, Number(msg?.dy) || 0);
    });
    this.onMessage(ClientMessage.Attack, (client, msg: AttackPayload) =>
      this.world.enqueue(client.sessionId, 'attack', msg ?? {}));
    this.onMessage(ClientMessage.UseAbility, (client, msg: UseAbilityPayload) =>
      this.world.enqueue(client.sessionId, 'ability', msg));
    this.onMessage(ClientMessage.Interact, (client, msg: InteractPayload) =>
      this.world.enqueue(client.sessionId, 'interact', msg ?? {}));

    this.onMessage(ClientMessage.PickClass, (client, msg: PickClassPayload) => {
      if (this.state.phase !== MatchPhase.Lobby) return;
      const p = this.state.players.get(client.sessionId);
      if (!p || !CLASS_IDS.includes(msg?.classId) || classTaken(this.state, msg.classId, client.sessionId)) return;
      applyClass(p, msg.classId);
    });

    this.onMessage(ClientMessage.Ready, (client) => {
      const p = this.state.players.get(client.sessionId);
      if (p) p.ready = true;
    });

    this.onMessage(ClientMessage.SpendSkillPoint, (client, msg: SpendSkillPointPayload) => {
      const p = this.state.players.get(client.sessionId);
      const slot = msg?.slot;
      if (!p || slot === undefined || slot < 0 || slot > 2 || p.skillPoints <= 0) return;
      const rank = p.ranks[slot] ?? 0;
      if (rank >= PROGRESSION.MAX_RANK) return;
      p.ranks[slot] = rank + 1;
      p.skillPoints -= 1;
    });
  }

  private tick(dtMs: number) {
    const s = this.state;
    if (s.phase === MatchPhase.Lobby) {
      const humans = [...s.players.values()].filter((p) => !p.isBot);
      if (humans.length > 0 && humans.every((p) => p.ready)) {
        fillWithBots(s);
        s.phase = MatchPhase.Countdown;
        this.countdownElapsed = 0;
      }
      return;
    }
    if (s.phase === MatchPhase.Countdown) {
      this.countdownElapsed += dtMs;
      if (this.countdownElapsed >= MATCH.COUNTDOWN_MS) this.world.start();
      return;
    }
    this.world.step(dtMs / 1000);
  }

  private assignClass(preferred?: ClassId): ClassId {
    if (preferred && CLASS_IDS.includes(preferred) && !classTaken(this.state, preferred, '')) return preferred;
    return CLASS_IDS.find((c) => !classTaken(this.state, c, '')) ?? 'tank';
  }
}

// ---------------------------------------------------------------- shared setup
// Exported so the harness builds matches exactly the way the room does.

export function createMatchState(roomCode: string): MatchState {
  const s = new MatchState();
  s.phase = MatchPhase.Lobby;
  s.outcome = Outcome.None;
  s.stage = 1;
  s.crystalsRequired = CRYSTALS.PER_STAGE[0]!;
  s.timeRemainingMs = MATCH.DURATION_MS;
  s.roomCode = roomCode;
  s.boss.x = MAP.BOSS_ZONE.x;
  s.boss.y = MAP.BOSS_ZONE.y;
  s.boss.hp = BOSS.HP_PER_LIFE;
  s.boss.maxHp = BOSS.HP_PER_LIFE;
  s.boss.lives = BOSS.LIVES;
  s.boss.vulnerable = false;
  s.boss.behaviour = 'shielded';
  return s;
}

export function addPlayer(s: MatchState, id: string, name: string, classId: ClassId, isBot: boolean): Player {
  const p = new Player();
  p.id = id;
  p.name = name;
  p.isBot = isBot;
  p.connected = !isBot;
  p.ready = isBot;
  p.x = MAP.BASE.x + (Math.random() - 0.5) * 80;
  p.y = MAP.BASE.y + (Math.random() - 0.5) * 80;
  p.lives = PLAYER.LIVES;
  p.alive = true;
  p.reviveCharges = PLAYER.REVIVE_CHARGES;
  p.skillPoints = PROGRESSION.STARTING_SKILL_POINTS;
  // Rank 1 in the first ability so every class can do its job from second one.
  p.ranks.push(1, 0, 0);
  p.cooldownReadyAtMs.push(0, 0, 0);
  applyClass(p, classId);
  s.players.set(id, p);
  return p;
}

export function fillWithBots(s: MatchState) {
  for (const classId of CLASS_IDS) {
    if (classTaken(s, classId, '')) continue;
    addPlayer(s, 'bot_' + classId, CLASSES[classId].name + ' (bot)', classId, true);
  }
}

export function classTaken(s: MatchState, classId: ClassId, exceptId: string) {
  for (const [id, p] of s.players) if (id !== exceptId && CLASS_IDS[p.classIndex] === classId) return true;
  return false;
}

export function applyClass(p: Player, classId: ClassId) {
  const spec = CLASSES[classId];
  p.classIndex = CLASS_IDS.indexOf(classId);
  p.maxHp = spec.maxHp;
  p.hp = spec.maxHp;
}

export function randomRoomCode(): string {
  let out = '';
  for (let i = 0; i < ROOM_CODE_LENGTH; i++)
    out += ROOM_CODE_ALPHABET[Math.floor(Math.random() * ROOM_CODE_ALPHABET.length)];
  return out;
}
