/**
 * Networked shell around WorldImpl: lobby, hero selection, countdown, joins,
 * disconnects, restart, message routing. All gameplay lives in systems.
 *
 * Owned by the integrator. Agents do not edit this file.
 */

import { Room, matchMaker, type Client } from 'colyseus';
import {
  BOSS, BOTS, CLASSES, CLASS_IDS, MAP, MATCH, PATCH_RATE, PLAYER, PROTOCOL_VERSION,
  ROOM_CODE_ALPHABET, ROOM_CODE_LENGTH, TICK_MS,
  ClientMessage, JoinError, MatchPhase, Outcome,
  type AttackPayload, type ClassId, type InteractPayload, type JoinOptions, type MovePayload,
  type PickClassPayload, type System, type UseAbilityPayload,
} from '@redbox/shared';
import { MatchState, Player } from '@redbox/shared/schema';
import { WorldImpl } from './world.js';

/** How long a hero's seat is held for a player whose connection dropped mid-match. */
const RECONNECT_WINDOW_S = 30;
/**
 * Once one human is ready, the match starts after this long even if others
 * never press ready: one AFK visitor must not block a public lobby forever.
 */
const LOBBY_AUTOSTART_MS = 15_000;
/** Attempts at drawing a room code no live room uses. */
const ROOM_CODE_TRIES = 20;
/** Uncaught room errors: log the first few in full, then one in this many. */
const ERROR_LOG_FULL = 5;
const ERROR_LOG_EVERY = 100;

export class HeistRoom extends Room<MatchState> {
  maxClients = MATCH.TEAM_SIZE;

  /** Set by index.ts: stub systems for the frontend, real systems otherwise. */
  static systemFactory: () => System[] = () => [];

  world!: WorldImpl;
  private countdownElapsed = 0;
  private lobbyReadyElapsed = 0;
  private uncaughtErrors = 0;

  // The code is always drawn here: a client-supplied code could name a room
  // that already exists and hijack joins meant for it.
  async onCreate(options: { private?: boolean } = {}) {
    const state = createMatchState(await freeRoomCode());
    this.setState(state);
    // The 4-char code IS the Colyseus room id, so friends can joinById(code).
    this.roomId = state.roomCode;
    // Private rooms are reachable only by code, never by quick-match.
    if (options.private) void this.setPrivate(true);
    this.setMetadata({ roomCode: state.roomCode });
    this.setPatchRate(1000 / PATCH_RATE);
    this.world = this.newWorld();
    this.registerMessageHandlers();
    // 0.16 has no fixed-timestep helper; clamp the measured delta so a GC hitch
    // can never teleport entities through walls.
    this.setSimulationInterval((deltaMs) => this.tick(Math.min(deltaMs, TICK_MS * 3)), TICK_MS);
  }

  private newWorld() {
    // Late async output (an LLM debrief resolving after Restart) belongs to the
    // world that asked for it; once replaced, that world goes silent.
    const world: WorldImpl = new WorldImpl(this.state, (type, payload) => {
      if (this.world === world) this.broadcast(type, payload);
    }, HeistRoom.systemFactory());
    return world;
  }

  onJoin(client: Client, options: JoinOptions) {
    // The thrown message is all a rejected client ever sees (messages sent
    // before a failed join are dropped), so it carries the details.
    if (options?.protocolVersion !== PROTOCOL_VERSION) {
      throw new Error(`${JoinError.ProtocolMismatch}: server v${PROTOCOL_VERSION}, client v${options?.protocolVersion}`);
    }
    if (this.state.phase !== MatchPhase.Lobby) throw new Error(JoinError.MatchInProgress);
    addPlayer(this.state, client.sessionId, options?.name || 'player', this.assignClass(options?.classId), false);
  }

  async onLeave(client: Client, consented?: boolean) {
    const p = this.state.players.get(client.sessionId);
    if (!p) return;
    if (this.state.phase === MatchPhase.Lobby) { this.state.players.delete(client.sessionId); return; }
    // Mid-match a bot takes the seat over, which is what movement.ts and
    // boxes.ts already expect from `!connected && isBot`: an idle hero would
    // otherwise stand in the field all match and cost the team a hero.
    p.connected = false;
    p.isBot = true;
    this.world.setIntent(p.id, 0, 0);

    // A dropped connection (not a deliberate leave) may come back and take
    // the hero over again. Holding the seat also keeps a solo room alive.
    if (consented || !client.reconnectionToken || this.state.phase === MatchPhase.Ended) return;
    try {
      await this.allowReconnection(client, RECONNECT_WINDOW_S);
    } catch {
      return; // Window expired: the bot keeps the seat.
    }
    this.rejoin(client.sessionId, p);
  }

  /** A reconnected player takes their hero back, or gets a fresh seat if a restart dropped it. */
  private rejoin(sessionId: string, p: Player) {
    if (this.state.players.get(sessionId) === p) {
      p.connected = true;
      p.isBot = false;
      this.world.setIntent(p.id, 0, 0);
    } else if (this.state.phase === MatchPhase.Lobby) {
      addPlayer(this.state, sessionId, p.name, this.assignClass(CLASS_IDS[p.classIndex]), false);
    }
  }

  /** Keep the room (and the process) alive through a bad tick or handler; log, rate-limited. */
  onUncaughtException(err: Error, methodName: string) {
    // Our own join refusals are expected; the client already gets the message.
    if (methodName === 'onJoin' && Object.values(JoinError).some((c) => err.message.startsWith(c))) return;
    this.uncaughtErrors++;
    if (this.uncaughtErrors <= ERROR_LOG_FULL) console.error(`[room ${this.roomId}] ${methodName}:`, err);
    else if (this.uncaughtErrors % ERROR_LOG_EVERY === 0) {
      console.error(`[room ${this.roomId}] ${methodName}: ${err.message} (${this.uncaughtErrors} errors so far)`);
    }
  }

  private registerMessageHandlers() {
    this.onMessage(ClientMessage.Move, (client, msg: MovePayload) => {
      this.world.setIntent(client.sessionId, finiteOr0(msg?.dx), finiteOr0(msg?.dy));
    });
    this.onMessage(ClientMessage.Attack, (client, msg: AttackPayload) =>
      this.world.enqueue(client.sessionId, 'attack', msg ?? {}));
    this.onMessage(ClientMessage.UseAbility, (client, msg: UseAbilityPayload) =>
      this.world.enqueue(client.sessionId, 'ability', msg));
    this.onMessage(ClientMessage.Interact, (client, msg: InteractPayload) =>
      this.world.enqueue(client.sessionId, 'interact', msg ?? {}));

    this.onMessage(ClientMessage.PickClass, (client, msg: PickClassPayload) => {
      if (this.state.phase !== MatchPhase.Lobby) return;
      const p = this.state.players.get(client.sessionId);
      if (!p || !CLASS_IDS.includes(msg?.classId) || classTaken(this.state, msg.classId, client.sessionId)) return;
      applyClass(p, msg.classId);
    });

    this.onMessage(ClientMessage.Ready, (client) => {
      const p = this.state.players.get(client.sessionId);
      if (p && this.state.phase === MatchPhase.Lobby) p.ready = true;
    });

    this.onMessage(ClientMessage.Restart, () => {
      if (this.state.phase !== MatchPhase.Ended) return;
      resetForRestart(this.state);
      void this.unlock();
      // Fresh systems: no closure state (timers, cooldown maps) survives a restart.
      this.world = this.newWorld();
    });
  }

  private tick(dtMs: number) {
    const s = this.state;
    if (s.phase === MatchPhase.Lobby) {
      const humans = [...s.players.values()].filter((p) => !p.isBot);
      const readyCount = humans.filter((p) => p.ready).length;
      this.lobbyReadyElapsed = readyCount > 0 ? this.lobbyReadyElapsed + dtMs : 0;
      const allReady = humans.length > 0 && readyCount === humans.length;
      if (allReady || (readyCount > 0 && this.lobbyReadyElapsed >= LOBBY_AUTOSTART_MS)) {
        // Whoever never pressed ready plays anyway: they are in the room.
        for (const p of humans) p.ready = true;
        this.lobbyReadyElapsed = 0;
        if (BOTS.FILL_EMPTY_SLOTS) fillWithBots(s);
        s.phase = MatchPhase.Countdown;
        // Once the match starts nobody can join, so take the room out of
        // quick-match; otherwise new visitors get sent here and rejected.
        void this.lock();
        this.countdownElapsed = 0;
      }
      return;
    }
    if (s.phase === MatchPhase.Countdown) {
      this.countdownElapsed += dtMs;
      if (this.countdownElapsed >= MATCH.COUNTDOWN_MS) this.world.start();
      return;
    }
    this.world.step(dtMs / 1000);
  }

  private assignClass(preferred?: ClassId): ClassId {
    if (preferred && CLASS_IDS.includes(preferred) && !classTaken(this.state, preferred, '')) return preferred;
    return CLASS_IDS.find((c) => !classTaken(this.state, c, '')) ?? 'mage';
  }
}

// ---------------------------------------------------------------- shared setup
// Exported so the harness builds matches exactly the way the room does.

export function createMatchState(roomCode: string): MatchState {
  const s = new MatchState();
  s.roomCode = roomCode;
  resetBoard(s);
  return s;
}

function resetBoard(s: MatchState) {
  s.phase = MatchPhase.Lobby;
  s.outcome = Outcome.None;
  s.elapsedMs = 0;
  s.timeRemainingMs = MATCH.DURATION_MS;
  s.stage = 1;
  s.boxesDelivered = 0;
  s.boxesRequired = 0;
  s.crystalsDestroyed = 0;
  s.bossDamageMult = 1;
  s.boxes.clear(); s.creeps.clear(); s.crystals.clear(); s.hazards.clear(); s.revives.clear();
  s.boss.x = MAP.BOSS_ZONE.x;
  s.boss.y = MAP.BOSS_ZONE.y;
  s.boss.hp = BOSS.HP;
  s.boss.maxHp = BOSS.HP;
  s.boss.alive = true;
  s.boss.targetId = '';
  s.boss.behaviour = 'idle';
  s.boss.attack = '';
  s.director.taunt = '';
  s.director.reasoning = '';
  s.director.source = '';
  s.director.focusClassIndex = -1;
}

/** Back to the lobby with the same party and heroes. Nothing stale survives. */
export function resetForRestart(s: MatchState) {
  resetBoard(s);
  for (const [id, p] of [...s.players]) {
    if (p.isBot || !p.connected) { s.players.delete(id); continue; }
    resetPlayer(p);
    p.ready = false;
  }
}

function resetPlayer(p: Player) {
  p.x = MAP.BASE.x + (Math.random() - 0.5) * 80;
  p.y = MAP.BASE.y + (Math.random() - 0.5) * 80;
  p.lives = PLAYER.LIVES;
  p.alive = true;
  p.hp = p.maxHp;
  p.respawnAtMs = 0;
  p.revivesLeft = PLAYER.REVIVES_PER_HERO;
  p.carryingBoxId = '';
  p.attackReadyAtMs = 0;
  p.threatShare = 0;
  p.moving = false;
  while (p.ranks.length) p.ranks.pop();
  p.ranks.push(1, 0, 0);
  while (p.cooldownReadyAtMs.length) p.cooldownReadyAtMs.pop();
  p.cooldownReadyAtMs.push(0, 0, 0);
}

export function addPlayer(s: MatchState, id: string, name: string, classId: ClassId, isBot: boolean): Player {
  const p = new Player();
  p.id = id;
  p.name = name;
  p.isBot = isBot;
  p.connected = !isBot;
  p.ready = isBot;
  applyClass(p, classId);
  resetPlayer(p);
  s.players.set(id, p);
  return p;
}

export function fillWithBots(s: MatchState) {
  for (const classId of CLASS_IDS) {
    if (classTaken(s, classId, '')) continue;
    addPlayer(s, 'bot_' + classId, CLASSES[classId].name + ' (bot)', classId, true);
  }
}

export function classTaken(s: MatchState, classId: ClassId, exceptId: string) {
  for (const [id, p] of s.players) if (id !== exceptId && CLASS_IDS[p.classIndex] === classId) return true;
  return false;
}

export function applyClass(p: Player, classId: ClassId) {
  const spec = CLASSES[classId];
  p.classIndex = CLASS_IDS.indexOf(classId);
  p.maxHp = spec.maxHp;
  p.hp = spec.maxHp;
}

/** Client input as a finite number: NaN, ±Infinity and non-numbers become 0. */
export function finiteOr0(v: unknown): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

/** A room code no live room is using (the code IS the room id). */
export async function freeRoomCode(): Promise<string> {
  let code = randomRoomCode();
  for (let i = 1; i < ROOM_CODE_TRIES && (await matchMaker.query({ roomId: code })).length > 0; i++) code = randomRoomCode();
  return code;
}

export function randomRoomCode(): string {
  let out = '';
  for (let i = 0; i < ROOM_CODE_LENGTH; i++)
    out += ROOM_CODE_ALPHABET[Math.floor(Math.random() * ROOM_CODE_ALPHABET.length)];
  return out;
}
