/**
 * The one implementation of `World`, shared by HeistRoom (networked) and the
 * headless Harness (tests). It also owns the wave flow, because a wave
 * transition clears every system's entities at once.
 *
 * Owned by the integrator. Agents do not edit this file.
 */

import {
  ARENA_H, ARENA_W, CLASS_BY_INDEX, COMBAT, DIRECTOR, GOBLINS, MAP, MATCH, PLAYER, TILE,
  WAVE_COUNT, BoxMark, MatchPhase, Outcome, ServerMessage,
  bossDamageMultiplier, isWallTile, toTile, tileCentre, wavePlan,
  type ClassId, type Command, type CommandKind, type CommandPayloadMap, type DamageOptions,
  type Entity, type EntityKind, type FxKind, type MatchEvent, type ModKey, type QueryOptions,
  type System, type Vec2, type World,
} from '@redbox/shared';
import {
  Creep, Hazard, ReviveResource, type Box, type MatchState, type Player,
} from '@redbox/shared/schema';

interface Intent { dx: number; dy: number; atMs: number; }

let idCounter = 0;
const nextId = (prefix: string) => `${prefix}${(++idCounter).toString(36)}`;
const NEIGHBOURS = [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [1, -1], [-1, 1], [-1, -1]] as const;
const FIELD_TTL_MS = 400;

export class WorldImpl implements World {
  now = 0;
  dt = 0;

  private boxTruth = new Map<string, boolean>();
  private threat = new Map<string, number>();
  private bias = new Map<ClassId, number>();
  private mods = new Map<string, Map<ModKey, { value: number; until: number }>>();
  private intents = new Map<string, Intent>();
  private pendingCommands: Command[] = [];
  private tickCommands: Command[] = [];
  private eventLog: MatchEvent[] = [];
  private fields = new Map<number, { dist: Int16Array; at: number }>();
  private transitionEndsAt = 0;

  constructor(
    readonly state: MatchState,
    private readonly send: (type: string, payload: unknown) => void,
    private readonly systems: System[] = [],
  ) {}

  get wave() { return this.state.stage; }

  // ================================================================ wave flow

  /** Enter wave 1. Called once when the countdown ends. */
  start() {
    this.state.phase = MatchPhase.Playing;
    this.state.elapsedMs = 0;
    this.state.timeRemainingMs = MATCH.DURATION_MS;
    this.now = 0;
    this.emit({ type: 'match_start', atMs: 0 });
    for (const s of this.systems) s.init?.(this);
    this.beginWave(1);
  }

  private beginWave(wave: number) {
    const s = this.state;
    const plan = wavePlan(wave);
    s.stage = wave;
    s.boxesDelivered = 0;
    s.boxesRequired = plan.requiredDeliveries;
    s.crystalsDestroyed = 0;
    s.bossDamageMult = bossDamageMultiplier(0);

    // The board resets; players keep their remaining lives.
    s.boxes.clear(); s.creeps.clear(); s.hazards.clear(); s.revives.clear(); s.crystals.clear();
    this.boxTruth.clear();
    this.threat.clear();
    this.mods.clear();
    for (const [, p] of s.players) {
      p.carryingBoxId = '';
      // Slot N unlocks at wave N+1 and never earlier.
      for (let slot = 0; slot < 3; slot++) p.ranks[slot] = slot < wave ? 1 : 0;
      for (let slot = 0; slot < 3; slot++) p.cooldownReadyAtMs[slot] = 0;
      p.attackReadyAtMs = 0;
      if (p.lives > 0) {
        const spot = this.nearestWalkable({ x: MAP.BASE.x + (Math.random() - 0.5) * 90, y: MAP.BASE.y + (Math.random() - 0.5) * 90 });
        p.x = spot.x; p.y = spot.y;
        p.alive = true; p.hp = p.maxHp; p.respawnAtMs = 0;
      }
    }

    this.emit({ type: 'wave_start', atMs: this.now, value: wave });
    for (const sys of this.systems) sys.onWaveStart?.(this);
  }

  /** Advance one tick. */
  step(dtSeconds: number) {
    const s = this.state;
    if (s.phase !== MatchPhase.Playing && s.phase !== MatchPhase.WaveTransition) return;
    this.dt = dtSeconds;
    s.elapsedMs = Math.round(s.elapsedMs + dtSeconds * 1000);
    this.now = s.elapsedMs;
    if (MATCH.DURATION_MS > 0) s.timeRemainingMs = Math.max(0, MATCH.DURATION_MS - s.elapsedMs);

    this.tickCommands = this.pendingCommands;
    this.pendingCommands = [];

    if (s.phase === MatchPhase.WaveTransition) {
      if (this.now >= this.transitionEndsAt) {
        s.phase = MatchPhase.Playing;
        this.beginWave(s.stage + 1);
      }
      return;
    }

    for (const sys of this.systems) {
      sys.update(this);
      if (s.phase !== MatchPhase.Playing) return;
    }
    this.publishThreatShare();

    // Delivery is the only way to clear a wave. Boss defeat alone never does.
    if (s.boxesDelivered >= s.boxesRequired && s.boxesRequired > 0) {
      this.emit({ type: 'wave_cleared', atMs: this.now, value: s.stage });
      this.fx('wave_cleared', MAP.BASE, { value: s.stage });
      if (s.stage >= WAVE_COUNT) { this.endMatch(Outcome.Victory); return; }
      s.phase = MatchPhase.WaveTransition;
      this.transitionEndsAt = this.now + MATCH.WAVE_TRANSITION_MS;
      return;
    }

    if (MATCH.DURATION_MS > 0 && s.timeRemainingMs === 0) this.endMatch(Outcome.Timeout);
  }

  /** Called by the room for every client message. */
  enqueue<K extends CommandKind>(playerId: string, kind: K, payload: CommandPayloadMap[K]) {
    this.pendingCommands.push({ kind, playerId, payload } as Command);
  }

  // ===================================================================== input

  commands<K extends CommandKind>(kind: K): Command<K>[] {
    return this.tickCommands.filter((c) => c.kind === kind) as Command<K>[];
  }
  command<K extends CommandKind>(playerId: string, kind: K, payload: CommandPayloadMap[K]) {
    this.tickCommands.push({ kind, playerId, payload } as Command);
  }
  setIntent(playerId: string, dx: number, dy: number) {
    const len = Math.hypot(dx, dy);
    const k = len > 1 ? 1 / len : 1;
    this.intents.set(playerId, { dx: dx * k, dy: dy * k, atMs: this.now });
  }
  intentFor(playerId: string): Vec2 | undefined {
    const i = this.intents.get(playerId);
    if (!i || this.now - i.atMs > PLAYER.INPUT_MAX_AGE_MS) return undefined;
    if (i.dx === 0 && i.dy === 0) return undefined;
    return { x: i.dx, y: i.dy };
  }

  // ==================================================================== crates

  addBox(box: Box, truth: { isReal: boolean }) {
    this.boxTruth.set(box.id, truth.isReal);
    box.mark = BoxMark.Unknown;
    this.state.boxes.set(box.id, box);
  }
  isBoxReal(boxId: string) { return this.boxTruth.get(boxId) === true; }

  // ===================================================================== space

  distance(a: Vec2, b: Vec2) { return Math.hypot(a.x - b.x, a.y - b.y); }

  directionTo(a: Vec2, b: Vec2): Vec2 {
    const dx = b.x - a.x, dy = b.y - a.y;
    const len = Math.hypot(dx, dy);
    return len < 1e-6 ? { x: 0, y: 0 } : { x: dx / len, y: dy / len };
  }

  walkable(x: number, y: number) {
    if (x < 0 || y < 0 || x >= MAP.WIDTH_PX || y >= MAP.HEIGHT_PX) return false;
    const { tx, ty } = toTile(x, y);
    return !isWallTile(tx, ty);
  }

  lineOfSight(a: Vec2, b: Vec2): boolean {
    const d = this.distance(a, b);
    const steps = Math.max(1, Math.ceil(d / (TILE / 4)));
    for (let i = 1; i < steps; i++) {
      const t = i / steps;
      if (!this.walkable(a.x + (b.x - a.x) * t, a.y + (b.y - a.y) * t)) return false;
    }
    return true;
  }

  /** BFS distance field toward a tile, cached briefly: many chasers share one target. */
  private fieldTo(tx: number, ty: number): Int16Array {
    const key = ty * ARENA_W + tx;
    const cached = this.fields.get(key);
    if (cached && this.now - cached.at < FIELD_TTL_MS) return cached.dist;
    const dist = new Int16Array(ARENA_W * ARENA_H).fill(-1);
    if (!isWallTile(tx, ty)) {
      const queue = [key];
      dist[key] = 0;
      for (let head = 0; head < queue.length; head++) {
        const cur = queue[head]!;
        const cx = cur % ARENA_W, cy = (cur / ARENA_W) | 0;
        for (let n = 0; n < 4; n++) {
          const nx = cx + NEIGHBOURS[n]![0], ny = cy + NEIGHBOURS[n]![1];
          if (isWallTile(nx, ny)) continue;
          const ni = ny * ARENA_W + nx;
          if (dist[ni] !== -1) continue;
          dist[ni] = dist[cur]! + 1;
          queue.push(ni);
        }
      }
    }
    this.fields.set(key, { dist, at: this.now });
    return dist;
  }

  nextStep(from: Vec2, to: Vec2): Vec2 {
    if (this.lineOfSight(from, to)) return this.directionTo(from, to);
    const t = toTile(to.x, to.y);
    const f = toTile(from.x, from.y);
    const dist = this.fieldTo(t.tx, t.ty);
    const here = dist[f.ty * ARENA_W + f.tx] ?? -1;
    if (here < 0) return this.directionTo(from, to);
    let best = here, bx = f.tx, by = f.ty;
    for (const [dx, dy] of NEIGHBOURS) {
      const nx = f.tx + dx, ny = f.ty + dy;
      if (isWallTile(nx, ny)) continue;
      // No corner cutting: a diagonal needs both orthogonal tiles open.
      if (dx !== 0 && dy !== 0 && (isWallTile(f.tx + dx, f.ty) || isWallTile(f.tx, f.ty + dy))) continue;
      const d = dist[ny * ARENA_W + nx] ?? -1;
      if (d >= 0 && d < best) { best = d; bx = nx; by = ny; }
    }
    return this.directionTo(from, tileCentre(bx, by));
  }

  reachable(from: Vec2, to: Vec2): boolean {
    const t = toTile(to.x, to.y);
    const f = toTile(from.x, from.y);
    return (this.fieldTo(t.tx, t.ty)[f.ty * ARENA_W + f.tx] ?? -1) >= 0;
  }

  nearestWalkable(p: Vec2): Vec2 {
    if (this.walkable(p.x, p.y)) return { x: p.x, y: p.y };
    const { tx, ty } = toTile(p.x, p.y);
    for (let r = 1; r < Math.max(ARENA_W, ARENA_H); r++)
      for (let dy = -r; dy <= r; dy++)
        for (let dx = -r; dx <= r; dx++) {
          if (Math.abs(dx) !== r && Math.abs(dy) !== r) continue;
          if (!isWallTile(tx + dx, ty + dy) && tx + dx > 0 && ty + dy > 0) return tileCentre(tx + dx, ty + dy);
        }
    return { x: MAP.BASE.x, y: MAP.BASE.y };
  }

  push(entityId: string, dir: Vec2, distance: number): number {
    if (entityId === 'boss' || this.modifier(entityId, 'knockbackImmune', 0) > 0) return 0;
    const found = this.findEntity(entityId);
    if (!found || (found.kind !== 'player' && found.kind !== 'creep')) return 0;
    const e = found.entity as { x: number; y: number };
    const len = Math.hypot(dir.x, dir.y) || 1;
    const ux = dir.x / len, uy = dir.y / len;
    let moved = 0;
    const stepPx = 4;
    while (moved + stepPx <= distance) {
      const nx = e.x + ux * stepPx, ny = e.y + uy * stepPx;
      if (!this.walkable(nx, ny)) break;
      e.x = nx; e.y = ny; moved += stepPx;
    }
    return moved;
  }

  query(centre: Vec2, radius: number, opts: QueryOptions): Entity[] {
    const s = this.state;
    const alive = opts.aliveOnly !== false;
    const near = (e: Vec2) => this.distance(centre, e) <= radius;
    const out: Entity[] = [];
    const want = (k: EntityKind) => opts.kinds.includes(k);
    const skip = (id: string) => id === opts.excludeId;
    if (want('player')) for (const [, p] of s.players) if ((!alive || p.alive) && !skip(p.id) && near(p)) out.push(p);
    if (want('creep')) for (const [, c] of s.creeps) if ((!alive || c.hp > 0) && !skip(c.id) && near(c)) out.push(c);
    if (want('crystal')) for (const [, c] of s.crystals) if ((!alive || !c.destroyed) && !skip(c.id) && near(c)) out.push(c);
    if (want('box')) for (const [, b] of s.boxes) if (!skip(b.id) && near(b)) out.push(b);
    if (want('revive')) for (const [, r] of s.revives) if ((!alive || !r.claimed) && near(r)) out.push(r);
    if (want('hazard')) for (const [, h] of s.hazards) if (!skip(h.id) && near(h)) out.push(h);
    if (want('boss') && (!alive || s.boss.alive) && !skip('boss') && near(s.boss)) out.push(s.boss);
    return out;
  }

  findEntity(id: string): { kind: EntityKind; entity: Entity } | undefined {
    const s = this.state;
    if (id === 'boss') return { kind: 'boss', entity: s.boss };
    const p = s.players.get(id); if (p) return { kind: 'player', entity: p };
    const c = s.creeps.get(id); if (c) return { kind: 'creep', entity: c };
    const k = s.crystals.get(id); if (k) return { kind: 'crystal', entity: k };
    const b = s.boxes.get(id); if (b) return { kind: 'box', entity: b };
    const r = s.revives.get(id); if (r) return { kind: 'revive', entity: r };
    const h = s.hazards.get(id); if (h) return { kind: 'hazard', entity: h };
    return undefined;
  }

  // ==================================================================== combat

  damage(targetId: string, amount: number, opts: DamageOptions = {}): number {
    if (!(amount > 0)) return 0;
    const s = this.state;
    const src = opts.sourceId;
    const fromPlayer = src !== undefined && s.players.has(src);
    // Outgoing buffs are applied centrally so every damage source respects them.
    if (fromPlayer) amount *= this.modifier(src!, 'damageDealtMult');

    if (targetId === 'boss') {
      if (!s.boss.alive || s.boss.hp <= 0) return 0;
      const dealt = Math.min(s.boss.hp, Math.round(amount * s.bossDamageMult * this.modifier('boss', 'damageTakenMult')));
      s.boss.hp -= dealt;
      if (fromPlayer) this.addThreat(src!, dealt);
      if (dealt > 0) this.fx('hit', s.boss, { sourceId: src, value: dealt });
      return dealt;
    }

    const player = s.players.get(targetId);
    if (player) {
      if (!player.alive) return 0;
      if (!COMBAT.FRIENDLY_FIRE && fromPlayer) return 0;
      const counter = this.modifier(player.id, 'parry', 0);
      if (counter > 0) {
        this.fx('parry', player, { sourceId: player.id });
        if (src && !fromPlayer) this.damage(src, counter, { sourceId: player.id });
        return 0;
      }
      const dealt = Math.min(player.hp, Math.round(amount * this.modifier(player.id, 'damageTakenMult')));
      player.hp -= dealt;
      if (dealt > 0) this.fx('hit', player, { sourceId: src, value: dealt });
      return dealt;
    }

    const creep = s.creeps.get(targetId);
    if (creep) {
      if (creep.hp <= 0) return 0;
      const dealt = Math.min(creep.hp, Math.round(amount));
      creep.hp -= dealt;
      if (dealt > 0) this.fx('hit', creep, { sourceId: src, value: dealt });
      return dealt;
    }

    const crystal = s.crystals.get(targetId);
    if (crystal) {
      if (crystal.destroyed) return 0;
      const dealt = Math.min(crystal.hp, Math.round(amount));
      crystal.hp -= dealt;
      if (dealt > 0) this.fx('hit', crystal, { sourceId: src, value: dealt });
      return dealt;
    }
    return 0;
  }

  heal(targetId: string, amount: number): number {
    const p = this.state.players.get(targetId);
    if (!p || !p.alive || amount <= 0) return 0;
    const healed = Math.min(p.maxHp - p.hp, Math.round(amount));
    p.hp += healed;
    if (healed > 0) this.fx('heal', p, { value: healed });
    return healed;
  }

  // ==================================================================== threat

  addThreat(playerId: string, amount: number) {
    this.threat.set(playerId, Math.max(0, (this.threat.get(playerId) ?? 0) + amount));
  }
  threatOf(playerId: string) { return this.threat.get(playerId) ?? 0; }
  threatEntries(): Array<[string, number]> { return [...this.threat.entries()]; }
  scaleAllThreat(factor: number) { for (const [id, t] of this.threat) this.threat.set(id, t * factor); }
  clearThreat(playerId: string) { this.threat.delete(playerId); }
  setThreatBias(classId: ClassId, mult: number) {
    this.bias.set(classId, Math.min(DIRECTOR.MAX_THREAT_BIAS, Math.max(DIRECTOR.MIN_THREAT_BIAS, mult)));
  }
  threatBias(classId: ClassId) { return this.bias.get(classId) ?? 1; }

  private publishThreatShare() {
    let total = 0;
    for (const [, t] of this.threat) total += t;
    for (const [id, p] of this.state.players) {
      const share = total > 0 ? (this.threat.get(id) ?? 0) / total : 0;
      if (Math.abs(p.threatShare - share) > 0.01) p.threatShare = share;
    }
  }

  // ================================================================= modifiers

  addModifier(entityId: string, key: ModKey, value: number, durationMs: number) {
    // The boss is never stun-locked: hard CC becomes a slow.
    if (entityId === 'boss' && key === 'stunned') { key = 'speedMult'; value = COMBAT.BOSS_CC_SLOW_MULT; }
    let m = this.mods.get(entityId);
    if (!m) this.mods.set(entityId, (m = new Map()));
    m.set(key, { value, until: this.now + durationMs });
  }
  modifier(entityId: string, key: ModKey, fallback = 1): number {
    const e = this.mods.get(entityId)?.get(key);
    if (!e) return fallback;
    if (e.until <= this.now) { this.mods.get(entityId)!.delete(key); return fallback; }
    return e.value;
  }
  clearModifiers(entityId: string) { this.mods.delete(entityId); }

  // ================================================================== entities

  spawnCreep(pos: Vec2, wave = this.wave): Creep {
    const at = this.nearestWalkable(pos);
    const c = new Creep();
    c.id = nextId('gob');
    c.x = at.x; c.y = at.y; c.tier = wave;
    // Born alive and pre-scaled: 1.00 / 1.20 / 1.30 of wave 1, never compounded.
    c.maxHp = c.hp = Math.round(GOBLINS.HP * wavePlan(wave).enemyMult);
    this.state.creeps.set(c.id, c);
    return c;
  }

  spawnRevive(pos: Vec2): ReviveResource {
    const at = this.nearestWalkable(pos);
    const r = new ReviveResource();
    r.id = nextId('rv');
    r.x = at.x; r.y = at.y;
    this.state.revives.set(r.id, r);
    return r;
  }

  spawnHazard(opts: { kind: string; pos: Vec2; radius: number; detonateAtMs: number; ownerId: string }): Hazard {
    const h = new Hazard();
    h.id = nextId('hz');
    h.kind = opts.kind;
    h.x = opts.pos.x; h.y = opts.pos.y;
    h.radius = Math.round(opts.radius);
    h.detonateAtMs = opts.detonateAtMs;
    h.ownerId = opts.ownerId;
    this.state.hazards.set(h.id, h);
    return h;
  }

  removeEntity(kind: EntityKind, id: string) {
    const s = this.state;
    if (kind === 'creep') s.creeps.delete(id);
    else if (kind === 'box') s.boxes.delete(id);
    else if (kind === 'crystal') s.crystals.delete(id);
    else if (kind === 'revive') s.revives.delete(id);
    else if (kind === 'hazard') s.hazards.delete(id);
    this.mods.delete(id);
  }

  // ==================================================================== output

  emit(e: MatchEvent) {
    this.eventLog.push(e);
    this.send(ServerMessage.Event, { event: e });
  }
  fx(kind: FxKind, pos: Vec2, opts: { sourceId?: string; value?: number; angle?: number } = {}) {
    this.send(ServerMessage.Fx, { kind, x: pos.x, y: pos.y, ...opts });
  }
  broadcast(type: string, payload: unknown) { this.send(type, payload); }
  recentEvents(n = 15) { return this.eventLog.slice(-n); }
  allEvents() { return this.eventLog; }

  // ===================================================================== match

  endMatch(outcome: number) {
    if (this.state.phase === MatchPhase.Ended) return;
    this.state.phase = MatchPhase.Ended;
    this.state.outcome = outcome;
    this.emit({ type: 'match_end', atMs: this.now, value: outcome });
    for (const sys of this.systems) sys.onEnd?.(this);
  }

  playersOfClass(classId: ClassId) {
    return [...this.state.players.values()].filter((p) => CLASS_BY_INDEX[p.classIndex] === classId);
  }
  alivePlayers(): Player[] {
    return [...this.state.players.values()].filter((p) => p.alive);
  }
}

