/**
 * The one implementation of `World`. Used by HeistRoom (networked) and by the
 * headless Harness (tests), so a system that passes in the harness behaves the
 * same in the real server.
 *
 * Owned by the integrator. Agents do not edit this file - if a capability is
 * missing, say so rather than reaching around it.
 */

import {
  BOSS, CLASS_BY_INDEX, CRYSTALS, DIRECTOR, MAP, MATCH, PLAYER, WAVES,
  BoxMark, MatchPhase, Outcome, ServerMessage,
  incomingDamageMultiplier,
  type ClassId, type Command, type CommandKind, type CommandPayloadMap, type DamageOptions,
  type Entity, type EntityKind, type FxKind, type MatchEvent, type ModKey, type QueryOptions,
  type System, type Vec2, type World,
} from '@redbox/shared';
import { Creep, ReviveResource, type Box, type MatchState, type Player } from '@redbox/shared/schema';

interface Intent { dx: number; dy: number; atMs: number; }

let idCounter = 0;
const nextId = (prefix: string) => `${prefix}${(++idCounter).toString(36)}`;

export class WorldImpl implements World {
  now = 0;
  dt = 0;

  private boxTruth = new Map<string, { isReal: boolean; camouflaged: boolean }>();
  private hiddenBoxes = new Map<string, Box>();
  private threat = new Map<string, number>();
  private bias = new Map<ClassId, number>();
  private mods = new Map<string, Map<ModKey, { value: number; until: number }>>();
  private intents = new Map<string, Intent>();
  private pendingCommands: Command[] = [];
  private tickCommands: Command[] = [];
  private eventLog: MatchEvent[] = [];

  constructor(
    readonly state: MatchState,
    private readonly send: (type: string, payload: unknown) => void,
    private readonly systems: System[] = [],
  ) {}

  // ================================================================= lifecycle

  /** Enter Playing and run every system's init. */
  start() {
    this.state.phase = MatchPhase.Playing;
    this.state.elapsedMs = 0;
    this.state.timeRemainingMs = MATCH.DURATION_MS;
    this.now = 0;
    this.emit({ type: 'match_start', atMs: 0 });
    for (const s of this.systems) s.init?.(this);
  }

  /** Advance one tick. Returns silently once the match has ended. */
  step(dtSeconds: number) {
    const s = this.state;
    if (s.phase !== MatchPhase.Playing) return;
    this.dt = dtSeconds;
    s.elapsedMs = Math.round(s.elapsedMs + dtSeconds * 1000);
    this.now = s.elapsedMs;
    s.timeRemainingMs = Math.max(0, MATCH.DURATION_MS - s.elapsedMs);

    this.tickCommands = this.pendingCommands;
    this.pendingCommands = [];

    for (const sys of this.systems) {
      sys.update(this);
      if (s.phase !== MatchPhase.Playing) return;
    }

    this.publishThreatShare();
    if (s.timeRemainingMs === 0) this.endMatch(Outcome.Timeout);
  }

  /** Called by the room for every client message. */
  enqueue<K extends CommandKind>(playerId: string, kind: K, payload: CommandPayloadMap[K]) {
    this.pendingCommands.push({ kind, playerId, payload } as Command);
  }

  // ===================================================================== input

  commands<K extends CommandKind>(kind: K): Command<K>[] {
    return this.tickCommands.filter((c) => c.kind === kind) as Command<K>[];
  }

  command<K extends CommandKind>(playerId: string, kind: K, payload: CommandPayloadMap[K]) {
    this.tickCommands.push({ kind, playerId, payload } as Command);
  }

  setIntent(playerId: string, dx: number, dy: number) {
    const len = Math.hypot(dx, dy);
    const k = len > 1 ? 1 / len : 1;
    this.intents.set(playerId, { dx: dx * k, dy: dy * k, atMs: this.now });
  }

  intentFor(playerId: string): Vec2 | undefined {
    const i = this.intents.get(playerId);
    if (!i || this.now - i.atMs > PLAYER.INPUT_MAX_AGE_MS) return undefined;
    if (i.dx === 0 && i.dy === 0) return undefined;
    return { x: i.dx, y: i.dy };
  }

  // ===================================================================== boxes

  addBox(box: Box, truth: { isReal: boolean; camouflaged: boolean }) {
    this.boxTruth.set(box.id, truth);
    box.mark = BoxMark.Unknown;
    if (truth.camouflaged) this.hiddenBoxes.set(box.id, box);
    else this.state.boxes.set(box.id, box);
  }

  isBoxReal(boxId: string) { return this.boxTruth.get(boxId)?.isReal === true; }

  scan(centre: Vec2, radius: number, byPlayerId: string): number {
    let revealed = 0;
    for (const [id, box] of [...this.hiddenBoxes]) {
      if (this.distance(centre, box) > radius) continue;
      this.hiddenBoxes.delete(id);
      this.state.boxes.set(id, box);
    }
    for (const [id, box] of this.state.boxes) {
      if (box.mark !== BoxMark.Unknown || this.distance(centre, box) > radius) continue;
      box.mark = this.isBoxReal(id) ? BoxMark.Real : BoxMark.Fake;
      revealed++;
    }
    this.emit({ type: 'scan_used', atMs: this.now, playerId: byPlayerId, value: revealed });
    this.fx('scan', centre, { sourceId: byPlayerId, value: radius });
    return revealed;
  }

  // =================================================================== spatial

  distance(a: Vec2, b: Vec2) { return Math.hypot(a.x - b.x, a.y - b.y); }

  nextStep(from: Vec2, to: Vec2): Vec2 {
    const dx = to.x - from.x, dy = to.y - from.y;
    const len = Math.hypot(dx, dy);
    return len < 1e-6 ? { x: 0, y: 0 } : { x: dx / len, y: dy / len };
  }

  walkable(x: number, y: number) {
    return x >= 0 && y >= 0 && x <= MAP.WIDTH_PX && y <= MAP.HEIGHT_PX;
  }

  query(centre: Vec2, radius: number, opts: QueryOptions): Entity[] {
    const s = this.state;
    const alive = opts.aliveOnly !== false;
    const near = (e: Vec2) => this.distance(centre, e) <= radius;
    const out: Entity[] = [];
    const want = (k: EntityKind) => opts.kinds.includes(k);
    if (want('player')) for (const [, p] of s.players)
      if ((!alive || p.alive) && p.id !== opts.excludeId && near(p)) out.push(p);
    if (want('creep')) for (const [, c] of s.creeps)
      if ((!alive || c.hp > 0) && c.id !== opts.excludeId && near(c)) out.push(c);
    if (want('crystal')) for (const [, c] of s.crystals)
      if ((!alive || !c.destroyed) && near(c)) out.push(c);
    if (want('box')) for (const [, b] of s.boxes) if (near(b)) out.push(b);
    if (want('revive')) for (const [, r] of s.revives) if ((!alive || !r.claimed) && near(r)) out.push(r);
    if (want('boss') && near(s.boss)) out.push(s.boss);
    return out;
  }

  findEntity(id: string): { kind: EntityKind; entity: Entity } | undefined {
    const s = this.state;
    if (id === 'boss') return { kind: 'boss', entity: s.boss };
    const p = s.players.get(id); if (p) return { kind: 'player', entity: p };
    const c = s.creeps.get(id); if (c) return { kind: 'creep', entity: c };
    const k = s.crystals.get(id); if (k) return { kind: 'crystal', entity: k };
    const b = s.boxes.get(id); if (b) return { kind: 'box', entity: b };
    const r = s.revives.get(id); if (r) return { kind: 'revive', entity: r };
    return undefined;
  }

  // ==================================================================== combat

  damage(targetId: string, amount: number, opts: DamageOptions = {}): number {
    if (amount <= 0) return 0;
    const s = this.state;
    const src = opts.sourceId ? s.players.get(opts.sourceId) : undefined;

    if (targetId === 'boss') {
      // Hitting a shielded boss still draws its attention: that is how the Tank holds aggro.
      if (src) this.addThreat(src.id, amount * BOSS.THREAT.PER_DAMAGE);
      if (!s.boss.vulnerable || s.boss.hp <= 0) return 0;
      const dealt = Math.min(s.boss.hp, Math.round(amount));
      s.boss.hp -= dealt;
      this.fx('hit', s.boss, { sourceId: opts.sourceId, value: dealt });
      return dealt;
    }

    const player = s.players.get(targetId);
    if (player) {
      if (!player.alive || player.phasedUntilMs > this.now) return 0;
      let incoming = amount * incomingDamageMultiplier(player, this.now)
        * this.modifier(player.id, 'damageTakenMult');
      if (!opts.ignoreShield && player.shield > 0) {
        const absorbed = Math.min(player.shield, Math.round(incoming));
        player.shield -= absorbed;
        incoming -= absorbed;
      }
      const dealt = Math.min(player.hp, Math.max(0, Math.round(incoming)));
      player.hp -= dealt;
      if (dealt > 0) this.fx('hit', player, { sourceId: opts.sourceId, value: dealt });
      return dealt;
    }

    const creep = s.creeps.get(targetId);
    if (creep) {
      const dealt = Math.min(creep.hp, Math.round(amount));
      creep.hp -= dealt;
      if (dealt > 0) this.fx('hit', creep, { sourceId: opts.sourceId, value: dealt });
      return dealt;
    }

    const crystal = s.crystals.get(targetId);
    if (crystal) {
      if (crystal.destroyed) return 0;
      if (CRYSTALS.RANGED_ONLY && !opts.fromRanged) return 0;
      const dealt = Math.min(crystal.hp, Math.round(amount));
      crystal.hp -= dealt;
      if (dealt > 0) this.fx('hit', crystal, { sourceId: opts.sourceId, value: dealt });
      return dealt;
    }
    return 0;
  }

  heal(targetId: string, amount: number, sourceId?: string): number {
    const p = this.state.players.get(targetId);
    if (!p || !p.alive || amount <= 0) return 0;
    const healed = Math.min(p.maxHp - p.hp, Math.round(amount));
    p.hp += healed;
    if (sourceId && healed > 0) this.addThreat(sourceId, healed * BOSS.THREAT.PER_HEAL);
    if (healed > 0) this.fx('heal', p, { sourceId, value: healed });
    return healed;
  }

  // ==================================================================== threat

  addThreat(playerId: string, amount: number) {
    this.threat.set(playerId, Math.max(0, (this.threat.get(playerId) ?? 0) + amount));
  }
  setThreatTop(playerId: string, overshoot: number) {
    const top = Math.max(0, ...this.threat.values());
    this.threat.set(playerId, top * (1 + overshoot) + 1);
  }
  threatOf(playerId: string) { return this.threat.get(playerId) ?? 0; }
  threatEntries(): Array<[string, number]> { return [...this.threat.entries()]; }
  scaleAllThreat(factor: number) {
    for (const [id, t] of this.threat) this.threat.set(id, t * factor);
  }
  clearThreat(playerId: string) { this.threat.delete(playerId); }
  setThreatBias(classId: ClassId, mult: number) {
    this.bias.set(classId, Math.min(DIRECTOR.MAX_THREAT_BIAS, Math.max(DIRECTOR.MIN_THREAT_BIAS, mult)));
  }
  threatBias(classId: ClassId) { return this.bias.get(classId) ?? 1; }

  private publishThreatShare() {
    let total = 0;
    for (const [, t] of this.threat) total += t;
    for (const [id, p] of this.state.players) {
      const share = total > 0 ? (this.threat.get(id) ?? 0) / total : 0;
      if (Math.abs(p.threatShare - share) > 0.01) p.threatShare = share;
    }
  }

  // ================================================================= modifiers

  addModifier(entityId: string, key: ModKey, value: number, durationMs: number) {
    let m = this.mods.get(entityId);
    if (!m) this.mods.set(entityId, (m = new Map()));
    m.set(key, { value, until: this.now + durationMs });
  }

  modifier(entityId: string, key: ModKey, fallback = 1): number {
    const e = this.mods.get(entityId)?.get(key);
    if (!e) return fallback;
    if (e.until <= this.now) { this.mods.get(entityId)!.delete(key); return fallback; }
    return e.value;
  }

  applyDebuff(playerId: string, debuff: 'damageAmp' | 'slow' | 'phase', durationMs: number) {
    const p = this.state.players.get(playerId);
    if (!p) return;
    const until = this.now + durationMs;
    if (debuff === 'damageAmp') p.damageAmpUntilMs = until;
    else if (debuff === 'slow') p.slowUntilMs = until;
    else p.phasedUntilMs = until;
  }

  clearDebuffs(playerId: string) {
    const p = this.state.players.get(playerId);
    if (!p) return;
    p.damageAmpUntilMs = 0;
    p.slowUntilMs = 0;
  }

  // ================================================================== entities

  spawnCreep(pos: Vec2, tier: number): Creep {
    const c = new Creep();
    c.id = nextId('cr');
    c.x = pos.x; c.y = pos.y; c.tier = tier;
    // Born alive: a creep with hp 0 would be culled by waves.ts on its first tick.
    c.maxHp = c.hp = Math.round(WAVES.CREEP_HP * (1 + 0.5 * Math.max(0, tier - 1)));
    this.state.creeps.set(c.id, c);
    return c;
  }

  spawnRevive(pos: Vec2): ReviveResource {
    const r = new ReviveResource();
    r.id = nextId('rv');
    r.x = pos.x; r.y = pos.y;
    this.state.revives.set(r.id, r);
    return r;
  }

  removeEntity(kind: EntityKind, id: string) {
    const s = this.state;
    if (kind === 'creep') s.creeps.delete(id);
    else if (kind === 'box') s.boxes.delete(id);
    else if (kind === 'crystal') s.crystals.delete(id);
    else if (kind === 'revive') s.revives.delete(id);
    this.mods.delete(id);
  }

  // ==================================================================== output

  emit(e: MatchEvent) {
    this.eventLog.push(e);
    this.send(ServerMessage.Event, { event: e });
  }
  fx(kind: FxKind, pos: Vec2, opts: { sourceId?: string; value?: number } = {}) {
    this.send(ServerMessage.Fx, { kind, x: pos.x, y: pos.y, ...opts });
  }
  broadcast(type: string, payload: unknown) { this.send(type, payload); }
  recentEvents(n = 15) { return this.eventLog.slice(-n); }
  allEvents() { return this.eventLog; }

  // =============================================================== progression

  awardSkillPoint(playerId: string, amount: number) {
    const p = this.state.players.get(playerId);
    if (p) p.skillPoints += amount;
  }
  awardTeamSkillPoint(amount: number) {
    for (const [, p] of this.state.players) p.skillPoints += amount;
  }

  endMatch(outcome: number) {
    if (this.state.phase === MatchPhase.Ended) return;
    this.state.phase = MatchPhase.Ended;
    this.state.outcome = outcome;
    this.emit({ type: 'match_end', atMs: this.now, value: outcome });
    for (const sys of this.systems) sys.onEnd?.(this);
  }

  playersOfClass(classId: ClassId) {
    return [...this.state.players.values()].filter((p) => CLASS_BY_INDEX[p.classIndex] === classId);
  }
  alivePlayers(): Player[] {
    return [...this.state.players.values()].filter((p) => p.alive);
  }
}
